### ISSUE TITLE
Presmerovanie na SK preklad

### ISSUE THREAD

**Issue by ricco386** [pyconsk/2019.pycon.sk#1]
V pripade ze uzivatel nezada presnu url ale iba root `/` presmerujme ho na `/sk/index.html`

**Comment by ricco386** [comment]
Live webstranka to riesi cez konfiguraciu webservera. Takze to ma nizku prioritu, ale bolo by fajn to mat kvoli lokalnemu developmentu, resp. pripadnemu deploymentu na GitHub pages...

**Comment by mreguly** [comment]
on it

**Comment by ricco386** [comment]
PR merged #24 
Thanks @mreguly
