### ISSUE TITLE
Add page: Why become a sponsor?

### ISSUE THREAD

**Issue by ricco386** [pyconsk/2019.pycon.sk#11]
# Why become a sponsor?

We need you — PyCon SK 2018 in Bratislava seeks for sponsors and partners!

PyCon is an annual gathering for the community using and developing the open-source Python programming language. The conference is completely organized by volunteers.

The members of the Python community organize a PyCon conference in their home countries regularly, PyCon will happen in Slovakia for the third time.

To ensure high-quality speakers and keep the tickets price available for everyone we need you, the sponsors, who allow the conference to take place.

Do not hesitate to contact us. We are flexible and willing to work with you to design a sponsorship package that is going to meet your business needs.

sponsors@pycon.sk

## Marketing

Looking for new users for your product? Such people can be found at PyCon - they also will look for new products and ideas.

## Recruitment

Are you looking for programmers? PyCon is the best place for meeting new talents. Many participants will be experienced developers looking for their next big career move.

## Audience

Want to get your message across to the people, so they talk about you? PyCon is a great opportunity. People in the Python community like to discover and share new things.

## Community

Looking for new contributors and partners for your open source project? PyCon is the place, where they also will look for you.

## Support

Are you using Python in your company? Support for community events is an excellent opportunity to contribute back.

---

# Prečo sa stať sponzorom?

Potrebujeme vás — PyCon SK 2018 v Bratislave hľadá sponzorov a partnerov!

PyCon je každoročné stretnutie komunity ľudí, ktorí používajú alebo vyvíjajú open source programovací jazyk Python. Konferencia je kompletne organizovaná dobrovoľníkmi.

Členovia Python komunity organizujú PyCon konferencie vo svojich domovských krajinách pravidelne. PyCon bude na Slovensku už po tretí raz.

Aby sme mohli zabezpečiť kvalitných prednášajúcich a pritom udržať cenu vstupeniek dostupnú pre každého, potrebujeme vás, sponzorov, ktorí umožnia túto konferenciu uskutočniť.

Neváhajte nás kedykoľvek kontaktovať. Sme flexibilní a ochotní spolupracovať a navrhnúť s vami balíček sponzorstva, ktorý splní vaše obchodné potreby.

sponsors@pycon.sk

## Marketing

Hľadáte nových používateľov pre váš produkt? Takých ľudí nájdete na PyCone - aj oni budú hľadať nové produkty a nápady.

## Nábor

Hľadáte programátorov? PyCon je to najlepšie miesto pre stretnutie nových talentov. Mnohí účastníci budú skúsení vývojári, ktorí hľadajú svoj ďalší veľký kariérny krok.

## Publikum

Chcete dostať svoje posolstvo medzi ľudí, aby sa o vás hovorilo? PyCon je na to skvelá príležitosť. Ľudia v Python komunite radi objavujú a zdieľajú nové veci.

## Komunita

Hľadáte nových prispievateľov a partnerov pre váš open source projekt? PyCon je miesto, kde aj oni budú hľadať vás.

## Podpora

Používate vo vašej firme Python? Podpora komunitných udalostí je výborná príležitosť ako prispieť späť.

**Comment by mreguly** [comment]
idem na to
