### ISSUE TITLE
Design the website

### ISSUE THREAD

**Issue by ricco386** [pyconsk/2019.pycon.sk#15]
Now we have just a blank bootstrap page, we need it to be more attractive.

Update the webpage look to make it more attractive. There are no limits (but all materials used have to be open source, or created and released under open source license, we gladly leave thank you note for the author in the footer). Committee will take a vote on final design by the end of the month.

If there will be more offers committee (volunteer organizers) will take a vote on final one at the end of the month.

You can take an inspiration from the websites of our friends in different countries: https://www.pycon.org/

**Comment by Akshay1910** [comment]
but what's the content of the website

**Comment by ricco386** [comment]
@Akshay1910 that's a good point sorry I didn't add the live site url: https://2019.pycon.sk/en/ there are issues #14 #13 #11 with more pages. We might have  more explanatory pages for sponsors and about the conference... Most content will be similar to the last years: https://2018.pycon.sk/en/

**Comment by ricco386** [comment]
New redesign in PR #48
