### ISSUE TITLE
Add page PyCon SK Recording Release

### ISSUE THREAD

**Issue by ricco386** [pyconsk/2019.pycon.sk#27]
PyCon SK Recording Release

Part of the motivation for PyCon SK is to help with Python education and advocacy in Slovakia and around the world. Accordingly, we intend to record all PyCon SK presentations and live stream and release the recordings on the web — see the http://pyvideo.org/ for one such venue.

By submitting your talk or workshop proposal, or by signing up to give a lightning talk, you agree to give permission to the SPy o.z. to record, edit, and release audio and/or video of your presentation. We might also perform interviews with poster presenters or attendees and require recording releases to publish them.

By default, the recording release checkbox is checked when submitting a proposal. If you wish to opt-out, uncheck the release checkbox, note that no recordings or live stream of your talk will be made. You cannot opt out of recording for lightning talks.

You agree to the following legalese, which certifies that you are the author of your presentation (or otherwise allowed to present it at PyCon), and which allows the SPy o.z. 1) to perform the necessary audio and video editing needed to prepare your presentation, and 2) to distribute the recordings to other people, including on YouTube, or video sites. Released under CC-BY license. It also allows other people to watch the recordings.

Legalese:

I certify that I, the Submitter, am authorized to license this proposal and its associated presentation (the "User Submission") to the SPy o.z. for use in association with PyCon SK 2019.

Specifically:

- I, the Submitter, certify that I am the creator (and own the copyright) of the User Submission. 

- I, the Submitter, hereby grant the SPy o.z. to publish User Submission and its audio/video recordings under CC-BY license.

- I, the Submitter, specifically affirm the right to perform the User Submissions on the SPy o.z. web sites or on other web sites designated by the PSF (including, but not necessarily limited to YouTube).

**Comment by ricco386** [comment]
This new page shouldnt have to be accessible from top menu. Just link if from the CfP page.

**Comment by mreguly** [comment]
I'll do it

**Comment by ricco386** [comment]
PR #31 merged.
Thanks @mreguly
