### ISSUE TITLE
Index page text

### ISSUE THREAD

**Issue by ricco386** [pyconsk/2019.pycon.sk#28]
The PyCon SK 2019 conference, which will take place in Bratislava, is the annual gathering for the community using and developing the open-source Python programming language. It is organized by the volunteers from the SPy o.z., civic association dedicated to advancing and promoting Python and other  Open  Source technologies and ideas. Through PyCon, the SPy o.z. advances its mission of growing the Slovak (and also international) community of Python programmers and Open Source supporters.

Because PyCon SK is backed by the non-profit SPy, we keep registration costs much lower than comparable technology conferences (or other conferences in neighbor countries) so that PyCon remains accessible to the widest group possible.

PyCon SK is a diverse conference dedicated to providing an enjoyable experience to everyone. Help us do this by following our code of conduct.

**Comment by mreguly** [comment]
I'll do it

**Comment by ricco386** [comment]
PR #30 closed
Thanks @mreguly
